## NUmpy rewrite of calculate_distance function

In [1]:
import math
def calculate_distance(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: list
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.
    Returns
    -------
    distance: float
        The distance between the two points.
    """
    distance = 0
    for i in range(3):
        dim_dist = (coord1[i] - coord2[i])
        if box_length:
            coord_dist = dim_dist - box_length * np.round(dim_dist / box_length)
        dim_dist = dim_dist**2
        distance += dim_dist
    distance = np.sqrt(distance)
    return distance


In [2]:
import numpy as np

point1 = np.array([0,0,0])

point2 = np.array([0,8,0])



In [3]:
calculate_distance(point1, point2)

8.0

In [4]:
dimensional_distance = point2 - point1

print(dimensional_distance)


dimensional_distance = point1 - point2
print(dimensional_distance)


[0 8 0]
[ 0 -8  0]


In [5]:
dd2 = dimensional_distance ** 2 

dd2_sum = dd2.sum()

distance = math.sqrt(dd2_sum)

print(distance)



8.0


In [17]:
import math
def calculate_distance_np(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: np.array
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.
    Returns
    -------
    distance: float
        The distance between the two points.
    """
    
    coord_dist = coord1 - coord2
    
    
    if box_length:
            coord_dist = coord_dist - box_length * np.round(coord_dist / box_length)
    
   

#how many axis it has 

    if coord_dist.ndim < 2:
        coord_dist = coord_dist.reshape(1,-1)





    coord_dist = coord_dist ** 2
    
    coord_dist_sum = coord_dist.sum(axis=1)
    
    distance = np.sqrt(coord_dist_sum)
    
    return distance

    
    


In [18]:
## Check your funtction w/assert statements


point_1 = np.array([0,0,0])

point_2 = np.array([1,0,0])

dist1 = calculate_distance_np(point_1, point_2)


assert dist1 == 1

point_1 = np.array([0,0,0])

point_2 = np.array([0,1,1])




dist2 = calculate_distance_np(point_1, point_2)

assert dist2 == math.sqrt(2)

In [22]:
coord_set1 = np.array([[0,0,0], [0, 1, 0]])

coord_set2 = np.array([[0, 8, 0], [0, 1.5, 0]])

In [23]:
calculate_distance_np(coord_set1, coord_set2, 10)

array([2. , 0.5])

In [24]:
coord_set1.ndim

2